### ISSUE TITLE
Clipboard support doesn't work since version d0f94c5b-ls79

### ISSUE THREAD

**Issue by loli71** [linuxserver/docker-webtop#98]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Clipboard support doesn't work since upgrade webtop in last version d0f94c5b-ls79, work fine in previous version 97c79edc-ls78
I'm using lscr.io/linuxserver/webtop:ubuntu-xfce

------------------------------

## Expected Behavior

You can access advanced features of the Guacamole remote desktop using ctrl+alt+shift enabling you to use remote copy/paste

## Current Behavior

When I do CTRL+C in the webtop, I should found the result of the clipboard in the guacamole windows using ctrl+alt+shift (or clicking the small circle on the left side of the screen)

The clipboard is empty in the guacamole windows by clicking the small circle on the left side of the screen, 

In the other way, If I put some text in the  guacamole windows, CTRL+V past the previous CTRL+C from webtop, not the value inside the guacamole clipboard  window, 

## Steps to Reproduce

1.  clicking the small circle on the left side of the screen to open guacamoleadvanced features
2.  Put some text inside text field
3.  clicking the small circle  to close guacamoleadvanced features
4.  Open mousepad in webtop
5.   do Ctrl+V to do past
6.   no past of the guacamole clipboard !!!

## Environment
**OS: synology
**CPU architecture: x86_64
**How docker service was installed:**

using docker-compose in portainer
## Command used to create docker container (run/create/compose/screenshot)

---
version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: webtop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
      - SUBFOLDER=/
      - KEYBOARD=fr-fr-azerty
    volumes:
      - /volume1/docker/webtop/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3014:3000
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    restart: unless-stopped

**Comment by berryk** [comment]
I am noticing the same thing that the clipboard does not work in the latest versions. 

Also sound does not work and at least for me it takes about 20 seconds for the desktop to appear compared to about 3 seconds with version 97c79edc-ls78.

I am using ubuntu-xfce, but have the same behavior in multiple other versions. 

Docker on linux, using docker-compose.

**Comment by loli71** [comment]
> Also sound does not work and at least for me it takes about 20 seconds for the desktop to appear compared to about 3 seconds with version 97c79edc-ls78.
Same thing for me regarding the delay for desktop to appear.

**Comment by thespad** [comment]
We're aware of the refresh delay and it'll be fixed in a future release, probably sometime next week depending on how the build pipelines shake out.

**Comment by thelamer** [comment]
This is functional and resolved as far as my testing. Is anyone else still experiencing this with the current images?

**Comment by loli71** [comment]
> This is functional and resolved as far as my testing. Is anyone else still experiencing this with the current images?

It seems to be ok for me now with the lasted image ether for copy/paste and regarding the delay for desktop to appear

**Comment by loli71** [comment]
All seems to be ok now with the lasted image (Linuxserver.io version:- b49d717a-ls52 Build-date:- 2022-11-28T22:52:47-06:00 ) ether for copy/paste and regarding the delay for desktop to appear
